### ISSUE TITLE
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.

### ISSUE THREAD

**Issue by confile** [goodow/realtime-json#2]
I included `<inherits name="com.goodow.realtime.json.Json" />`in my GWT  2.7 project. When I do GWT compile in eclipse there is no error. When I run the app in SuperDevMode and the browser triggers a recompile I get the following errors: 

```
        Compiling 1 permutation
            Compiling permutation 0...
            [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
    at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:140)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:132)
    at com.google.gwt.dev.jjs.impl.Devirtualizer.getStaticImpl(Devirtualizer.java:562)
    at com.google.gwt.dev.jjs.impl.Devirtualizer.access$400(Devirtualizer.java:75)
    at com.google.gwt.dev.jjs.impl.Devirtualizer$RewriteVirtualDispatches.ensureDevirtualVersionExists(Devirtualizer.java:184)
    at com.google.gwt.dev.jjs.impl.Devirtualizer$RewriteVirtualDispatches.endVisit(Devirtualizer.java:101)
    at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:580)
    at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:183)
    at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:355)
    at com.google.gwt.dev.jjs.ast.JInterfaceType.traverse(JInterfaceType.java:75)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:284)
    at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1192)
    at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1156)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:380)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:292)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:284)
    at com.google.gwt.dev.jjs.impl.Devirtualizer.execImpl(Devirtualizer.java:320)
    at com.google.gwt.dev.jjs.impl.Devirtualizer.exec(Devirtualizer.java:218)
    at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler$MonolithicPermutationCompiler.normalizeSemantics(MonolithicJavaToJavaScriptCompiler.java:95)
    at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$PermutationCompiler.compilePermutation(JavaToJavaScriptCompiler.java:290)
    at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.compilePermutation(MonolithicJavaToJavaScriptCompiler.java:296)
    at com.google.gwt.dev.jjs.UnifiedAst.compilePermutation(UnifiedAst.java:143)
    at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:197)
    at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
    at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
    ... 27 more
               [ERROR] <no source info>: <source info not available>
               [ERROR] at JsonElement.java(19): public abstract JsonElement clear();

                  com.google.gwt.dev.jjs.ast.JMethod
               [ERROR] at JsonElement.java(18): interface JsonElement extends Serializable 
                  com.google.gwt.dev.jjs.ast.JInterfaceType
               [ERROR] at Unknown(0): <JProgram>
                  com.google.gwt.dev.jjs.ast.JProgram
            [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
    at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
    at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$PermutationCompiler.compilePermutation(JavaToJavaScriptCompiler.java:367)
    at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.compilePermutation(MonolithicJavaToJavaScriptCompiler.java:296)
    at com.google.gwt.dev.jjs.UnifiedAst.compilePermutation(UnifiedAst.java:143)
    at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:197)
    at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
    at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
    at java.lang.Thread.run(Thread.java:745)
            [ERROR] Not all permutation were compiled , completed (0/1)
      [WARN] recompile failed
      [WARN] continuing to serve previous version
```

**Comment by drmichaelgorski** [comment]
@larrytin I created a sample project to show this error: https://github.com/confile/Realtime-JSON-Test

**Comment by larrytin** [comment]
[ERROR]  no source info

So, add [realtime-json-0.5.0-sources.jar](https://oss.sonatype.org/#nexus-search;gav~~realtime-json~0.5.5-SNAPSHOT~~sources) to your classpath.

**Comment by drmichaelgorski** [comment]
I have these two libs (https://github.com/confile/Realtime-JSON-Test/tree/master/lib) on my build path. It compiles without problems but in super dev mode it raises this error.

**Comment by larrytin** [comment]
I do NOT use Eclipse, can you show me the picture of your superdev launch settings?

**Comment by drmichaelgorski** [comment]
Sure here is it: 

![run_configurations](https://cloud.githubusercontent.com/assets/64265/6119769/a5ca7790-b0cd-11e4-90a0-79dda4d28930.png)

![run_configurations](https://cloud.githubusercontent.com/assets/64265/6119776/b68781ea-b0cd-11e4-8693-11a0e9d49a04.png)

![run_configurations](https://cloud.githubusercontent.com/assets/64265/6119778/bff698ba-b0cd-11e4-924a-a00a89e88ca0.png)

![run_configurations](https://cloud.githubusercontent.com/assets/64265/6119782/c836ad1c-b0cd-11e4-9f73-97b6c1259b7f.png)

![run_configurations](https://cloud.githubusercontent.com/assets/64265/6119788/d03d7b4e-b0cd-11e4-835b-2f0f6ad9d35c.png)

**Comment by larrytin** [comment]
In the Classpath tab -> Add JARs... -> select realtime-json-0.5.0-sources.jar

**Comment by drmichaelgorski** [comment]
I tried this same error: 

![run_configurations](https://cloud.githubusercontent.com/assets/64265/6119827/780ae8fc-b0ce-11e4-8742-37f518a31ff2.png)

**Comment by larrytin** [comment]
Try [Launching Super Dev Mode Without Dev Mode](http://www.gwtproject.org/articles/superdevmode.html) using the main class com.google.gwt.dev.codeserver.CodeServer in gwt-codeserver.jar.

**Comment by drmichaelgorski** [comment]
I also created a GWT gradle project without Eclipse and got the same error. Have a look here: 

https://github.com/confile/JSON-Test

What do you do to make it work with SuperDevMode for you?

**Comment by larrytin** [comment]
I use [bash shell](https://github.com/goodow/realtime-channel/blob/master/gwt-compile.sh) and [gwt-maven-plugin](https://github.com/goodow/realtime-channel/blob/master/pom.xml).

Which gradle command should i use to execute?

**Comment by drmichaelgorski** [comment]
Use: 
- gradle clean
- gradle build
- gradle gwtDev

**Comment by larrytin** [comment]
Copy all the source files of realtime-json to your project and try again.

**Comment by drmichaelgorski** [comment]
I think I found the problem: [Overriding one package implementation with another](http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html)

> One caveat specific to overriding JRE classes in this way is that they will never actually be used in development mode. In development mode, the native JRE classes always supercede classes compiled from source. 

`super-source`will not be used in dev mode. I do not know if this includes super dev mode. 

How do you manage to run SuperDevMode without errors?

**Comment by drmichaelgorski** [comment]
@larrytin I still have problems using your plugin in super dev mode. Could you please publish a configuration how to use it?

**Comment by steffimueller** [comment]
@larrytin I have the same problem. Is there any workaround. I think the problem is that you use super source in your gwt.xml file. This might cause the problem in SDM. Is there a workaround or can you do it without super source?

**Comment by FrankNWalter** [comment]
+1

**Comment by FrankNWalter** [comment]
We experience the same probelm. We tried to add

```

    <replace-with class="com.goodow.realtime.json.js.JsJsonElement">
        <when-type-is class="com.goodow.realtime.json.JsonElement"/>
    </replace-with>
```

Still it gives the same error. So far it seems that this library is not working with GWT. Any statement from the author would be helpful.

**Comment by larrytin** [comment]
Sorry for the delay, we all immersed in the gaiety of Chinese New Year.

**Comment by larrytin** [comment]
@confile @steffimueller @FrankNWalter Does 69022c48a76e25575e61b0f7c788d45ad54cae02 work for you?

**Comment by drmichaelgorski** [comment]
Yes this Issue is solved.
